// const teamNames = {
//    ARI: "Arizona Cardinals",
//    ATL: "Atlanta Falcons",
//    BAL: "Baltimore Ravens",
//    BUF: "Buffalo Bills",
//    CAR: "Carolina Panthers",
//    CHI: "Chicago Bears",
//    CIN: "Cincinnati Bengals",
//    CLE: "Cleveland Browns",
//    DAL: "Dallas Cowboys",
//    DEN: "Denver Broncos",
//    DET: "Detroit Lions",
//    GB: "Green Bay Packers",
//    HOU: "Houston Texans",
//    IND: "Indianapolis Colts",
//    JAX: "Jacksonville Jaguars",
//    KC: "Kansas City Chiefs",
//    LV: "Las Vegas Raiders",
//    LAC: "Los Angeles Chargers",
//    LAR: "Los Angeles Rams",
//    MIA: "Miami Dolphins",
//    MIN: "Minnesota Vikings",
//    NE: "New England Patriots",
//    NO: "New Orleans Saints",
//    NYG: "New York Giants",
//    NYJ: "New York Jets",
//    PHI: "Philadelphia Eagles",
//    PIT: "Pittsburgh Steelers",
//    SF: "San Francisco 49ers",
//    SEA: "Seattle Seahawks",
//    TB: "Tampa Bay Buccaneers",
//    TEN: "Tennessee Titans",
//    WAS: "Washington Football Team",
// };

const teamNames = {
   ARI: "Cardinals",
   ATL: "Falcons",
   BAL: "Ravens",
   BUF: "Bills",
   CAR: "Panthers",
   CHI: "Bears",
   CIN: "Bengals",
   CLE: "Browns",
   DAL: "Cowboys",
   DEN: "Broncos",
   DET: "Lions",
   GB: "Packers",
   HOU: "Texans",
   IND: "Colts",
   JAX: "Jaguars",
   KC: "Chiefs",
   LV: "Raiders",
   LAC: "Chargers",
   LAR: "Rams",
   MIA: "Dolphins",
   MIN: "Vikings",
   NE: "Patriots",
   NO: "Saints",
   NYG: "Giants",
   NYJ: "Jets",
   PHI: "Eagles",
   PIT: "Steelers",
   SF: "49ers",
   SEA: "Seahawks",
   TB: "Buccaneers",
   TEN: "Titans",
   WAS: "Football Team",
};

export default teamNames;
